---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster 
  region: us-east-1
  version: "1.22"

managedNodeGroups:
  - name: system-ng
    instanceType: t3.medium
    desiredCapacity: 2    

availabilityZones: ['us-east-1a', 'us-east-1b']

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    # Confirm that AWSLoadBalancerControllerIAMPolicy exists in your account. If it doesn't execute the following commands to create it:
    #     curl -o iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.3.1/docs/install/iam_policy.json
    #     aws iam create-policy --policy-name AWSLoadBalancerControllerIAMPolicy --policy-document file://iam-policy.json
    # Swap the Policy ARN below with your own AWS account
    # i.e. arn:aws:iam::(your_aws_account_number_here):policy/AWSLoadBalancerControllerIAMPolicy
    attachPolicyARNs:
    - arn:aws:iam::511620223753:policy/AWSLoadBalancerControllerIAMPolicy
    roleOnly: true

